### ISSUE TITLE
feature request: http class

### ISSUE THREAD

**Issue by hanoii** [flourishlib/flourish-classes#171] opened 2012-11-30 13:22 UTC
Class for making with http requests, post request, follow redirections, etc. Might be an useful class to add.

**Comment by Dazzel** [comment] 2012-12-01 10:42
Does already exists; fRequest.

**Comment by hanoii** [comment] 2012-12-01 12:39
fRequest is for dealing with http request, I was more meaning to "making¨ http request, either via curl or some other method so you could retrieve a file or interact with a REST API for instance.

**Comment by wbond** [comment] 2012-12-03 14:49
This is a duplicate of #9

**Closed as completed by wbond** 2012-12-03 14:49 UTC
